#config
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-resources
  profiles:
    active: native
server:
  port: 8888
#eureka
spring:
  application:
    name: eureka-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#gateway
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
#service
spring:
  application:
    name: employee-service
  config:
    import: optional:configserver:http://localhost:8888
#repo
#gateway-service
spring:
  #4. Tạo định tuyến
  #Đăng ký route tĩnh:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: department-service
              uri: lb://department-service
              predicates:
                - Path=/api/department/**
              filters:
                - StripPrefix=1

            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/api/employee/**
              filters:
                - StripPrefix=1


#1. Đặt port cho gateway-service
server:
  port: 8080
#2. Đăng ký với eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#service

spring:
  application:
    name: department-service
  #datasource:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/department_db
    username: root
    password: 1234$
  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8086

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    should-unregister-on-shutdown: true
  instance:
    prefer-ip-address: true

